import { Geist, Geist_Mono } from "next/font/google";
import "./Style/globals.css";
import "./Style/responsive.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Kwiq 24",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/Favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Prevent hydration issues */}
        <meta name="format-detection" content="telephone=no" />
        <meta name="format-detection" content="date=no" />
        <meta name="format-detection" content="address=no" />
        <meta name="format-detection" content="email=no" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <div id="root">
          {/* ✅ Navbar on all pages */}
          <Navbar />

          {/* ✅ Page content */}
          <main>{children}</main>

          {/* ✅ Footer on all pages */}
          <Footer />
        </div>

        {/* Script to prevent extension interference */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if (typeof window !== 'undefined') {
                window.__NEXT_HYDRATION_CB = window.__NEXT_HYDRATION_CB || function() {};
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
          