import { Geist, Geist_Mono } from "next/font/google";
import "./Style/globals.css";
import "./Style/responsive.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap', // Add display swap for better loading
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap', // Add display swap for better loading
});

export const metadata = {
  title: "Kwiq 24",
  description: "Generated by create next app",
  icons: { 
    icon: "/icons/Favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add meta tag to prevent hydration issues with extensions */}
        <meta name="format-detection" content="telephone=no" />
        <meta name="format-detection" content="date=no" />
        <meta name="format-detection" content="address=no" />
        <meta name="format-detection" content="email=no" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <div id="root">
          {children}
        </div>
        
        {/* Script to prevent extension interference */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Prevent browser extension interference
              if (typeof window !== 'undefined') {
                window.__NEXT_HYDRATION_CB = window.__NEXT_HYDRATION_CB || function() {};
              }
            `,
          }}
        />
      </body>
    </html>
  );
}